### PR TITLE
Update DCO to v1.1

### PR DESCRIPTION
**Pull request by williamkapke**
See: https://github.com/nodejs/TSC/issues/92

### CODE REVIEW

**Comment by Starefossen** [comment]
LGTM

**Comment by williamkapke** [comment]
Let's merge it! 👍

**Comment by cheema38** [comment]
go go go!!! @ @ @ @

**Comment by williamkapke** [comment]
This is the last one in the org. Can someone plz hit Merge?

**Comment by Fishrock123** [comment]
done

**Pull request merged**
